package com.github.paohaijiao;

import com.github.paohaijiao.config.ThemeConfig;
import com.github.paohaijiao.enums.RelationshipType;
import com.github.paohaijiao.generator.ERDiagramSVGGenerator;
import com.github.paohaijiao.model.Column;
import com.github.paohaijiao.model.ERDiagram;
import com.github.paohaijiao.model.Table;
import com.github.paohaijiao.relation.Relationship;

import java.util.Date;

public class ERDiagramDemo {
    public static void main(String[] args) {
        try {
            // 创建ER图
            ERDiagram diagram = new ERDiagram();
            diagram.setTitle("订单系统数据库设计");
            diagram.setSize(1600, 1000); // 增大画布尺寸

            // 创建表格
            Table usersTable = new Table("用户表");
            usersTable.setComment("系统用户信息");
            usersTable.addColumn(new Column("用户ID", "INT"));
            usersTable.addColumn(new Column("用户名", "VARCHAR(50)"));
            usersTable.addColumn(new Column("邮箱", "VARCHAR(100)"));
            usersTable.addColumn(new Column("密码", "VARCHAR(100)"));
            usersTable.addColumn(new Column("创建时间", "DATETIME"));
            usersTable.getColumn("用户ID");//.setPrimaryKey(true);
            usersTable.getColumn("用户名");//.setNullable(false);
            usersTable.getColumn("邮箱");////.setNullable(false);

            Table productsTable = new Table("商品表");
            productsTable.setComment("商品信息");
            productsTable.addColumn(new Column("商品ID", "INT"));
            productsTable.addColumn(new Column("商品名称", "VARCHAR(100)"));
            productsTable.addColumn(new Column("价格", "DECIMAL(10,2)"));
            productsTable.addColumn(new Column("库存", "INT"));
            productsTable.addColumn(new Column("分类", "VARCHAR(50)"));
            productsTable.getColumn("商品ID");//.setPrimaryKey(true);
            productsTable.getColumn("商品名称");//.setNullable(false);
            productsTable.getColumn("价格");//.setNullable(false);

            Table ordersTable = new Table("订单表");
            ordersTable.setComment("用户订单");
            ordersTable.addColumn(new Column("订单ID", "INT"));
            ordersTable.addColumn(new Column("用户ID", "INT"));
            ordersTable.addColumn(new Column("订单金额", "DECIMAL(10,2)"));
            ordersTable.addColumn(new Column("状态", "VARCHAR(20)"));
            ordersTable.addColumn(new Column("下单时间", "DATETIME"));
            ordersTable.getColumn("订单ID").setPrimaryKey(true);
            ordersTable.getColumn("用户ID").setForeignKey(true);
            ordersTable.getColumn("订单金额").setNullable(false);
            ordersTable.getColumn("下单时间").setNullable(false);

            Table orderItemsTable = new Table("订单明细表");
            orderItemsTable.setComment("订单商品明细");
            orderItemsTable.addColumn(new Column("明细ID", "INT"));
            orderItemsTable.addColumn(new Column("订单ID", "INT"));
            orderItemsTable.addColumn(new Column("商品ID", "INT"));
            orderItemsTable.addColumn(new Column("数量", "INT"));
            orderItemsTable.addColumn(new Column("单价", "DECIMAL(10,2)"));
            orderItemsTable.getColumn("明细ID").setPrimaryKey(true);
            orderItemsTable.getColumn("订单ID").setForeignKey(true);
            orderItemsTable.getColumn("商品ID").setForeignKey(true);
            orderItemsTable.getColumn("数量").setNullable(false);

            // 添加到ER图
            diagram.addTable(usersTable);
            diagram.addTable(productsTable);
            diagram.addTable(ordersTable);
            diagram.addTable(orderItemsTable);
            // 创建关系
            Relationship rel1 = new Relationship("订单表", "用户ID", "用户表", "用户ID", RelationshipType.ONE_TO_MANY);
            rel1.setLabel("1:N");
            Relationship rel2 = new Relationship("订单明细表", "订单ID", "订单表", "订单ID", RelationshipType.ONE_TO_MANY);
            rel2.setLabel("1:N");
            Relationship rel3 = new Relationship("订单明细表", "商品ID", "商品表", "商品ID", RelationshipType.ONE_TO_MANY);
            rel3.setLabel("1:N");
            // 添加到ER图
            diagram.addRelationship(rel1);
            diagram.addRelationship(rel2);
            diagram.addRelationship(rel3);
            // 创建SVG生成器
            ERDiagramSVGGenerator generator = new ERDiagramSVGGenerator();
            // 配置生成器
            generator.setDiagramName("数据库ER图");
            generator.setWatermark("Generated by ER Diagram Tool");
            generator.setGenerationDate(new Date());
            generator.setTableSpacing(200); // 增加表格间距
            // 自定义主题
            ThemeConfig theme = new ThemeConfig();
            // 调整表格大小，确保文字能完整显示
            usersTable.setSize(320, 180);
            productsTable.setSize(320, 180);
            ordersTable.setSize(320, 180);
            orderItemsTable.setSize(320, 180);
            generator.setThemeConfig(theme);
            // 生成SVG
            generator.generateSVG(diagram, "d://test//er_diagram_fixed_v2.svg");
            System.out.println("修复版ER图生成成功: er_diagram_fixed_v2.svg");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
